GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJXZW1weSBWaXJnYW5hIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjQ3NDUyNDQ5LCJleHAiOjE2NDc0NTI0NjR9.Zm0y5eHuEX6cWmDf6y4U6v1A09uru0XPkVqMt1jH42Q

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Wempy Virgana",
    "email" : "test@test.com",
    "password" : "123456",
    "confPassword" : "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password" :"123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout



###

POST http://localhost:5000/customer
Content-Type: application/json

{
    "user_id":2,
    "name_customer":"Murid siapa",
    "whatsapp_number":"087742781223",
    "address":"Jalan in males ah"
}

###
GET  http://localhost:5000/customer/3

###
PATCH http://localhost:5000/transaction/13
Content-Type: application/json

{

    "transaction_unique":"BUKULAUNDRY1229",
    "user_id":2,
    "name_customer":"Wempy Virgana UPDATED",
    "address":"Jalan Gatot subroto",
    "whatsapp_number":"087742781223",
    "total_weight":4,
    "total_bill":5000,
    "status_payment":"PENDING",
    "type_laundry":"CUCI + GOSOK",
    "status_laundry":"WASHING",
    "additional_bill":5000,
    "service":true,
    "status_on_demand":"SEDANG DI ANTAR",
    "detail_item":[{"name_item":"Baju Kaos","total":5},{"name_item":"Baju Batik","total":2}]
}

###
GET  http://localhost:5000/getlaundry/laundri77671